variables:
#   Developers are not expected to actually use this CI image locally, however,
#   using this image avoid downloading a bunch of PyPI packages for each CI run.
  - &ci_image 'cont-reg.bjodah.se:443/bjodah/triceratops-6:32'

when:
  - event: [push, pull_request]

steps:

  - name: restore-cache
    image: *ci_image
    commands:
      - curl ftp://chempy:$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/cache-ci.tar | tar x
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/chempy

  - name: test-suite
    image: *ci_image
    environment:
      - CHEMPY_SKIP_NO_TESTS=1
    commands:
      - mkdir -p deploy/public_html/branches/${CI_COMMIT_BRANCH}/
      - bash -l .ci/run-01-install-deps-create-sdist.sh
      - bash -l .ci/run-02-test-suite.sh
      - mkdir -p deploy/public_html/branches/${CI_COMMIT_BRANCH}
      - cp dist/chempy-* deploy/public_html/branches/${CI_COMMIT_BRANCH}/


  - name: render-notebooks
    image: *ci_image
    environment:
      - CHEMPY_DEPRECATION_FILTER=ignore
    commands:
      - mkdir -p deploy/public_html/branches/${CI_COMMIT_BRANCH}/
      - bash -l .ci/run-01-install-deps-create-sdist.sh
      - bash -l .ci/run-03-render-notebooks.sh
      - .ci/grep-for-binary-data.sh

  - name: compile-documentation
    image: *ci_image
    environment:
      - CHEMPY_DEPRECATION_FILTER=ignore
    commands:
      - bash -lc '. .ci/_source_common_env.sh; ./scripts/generate_docs.sh'
      - cp LICENSE doc/_build/html/
      - cp -r doc/_build/html/ deploy/public_html/branches/${CI_COMMIT_BRANCH}
    depends_on:
      - test-suite
      - render-notebooks

  - name: rebuild-cache
    image: *ci_image
    commands:
      - find ./cache-ci/ -type f -mtime +90 -exec rm {} \;
      - tar cf cache-ci.tar ./cache-ci/
      - curl -T cache-ci.tar ftp://chempy:$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/chempy
    depends_on:
      - compile-documentation

  - name: deploy-public-html
    image: *ci_image
    commands:
      - tar czf chempy-${CI_COMMIT_BRANCH}.tar.gz ./deploy/public_html
      - curl -T chempy-${CI_COMMIT_BRANCH}.tar.gz ftp://chempy:$${ARTIFACTS_PASS}@$${FTP_SERVER}/public_html/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/chempy
    depends_on:
      - compile-documentation
